package com.alibaba.fastjson3.reader;

import com.alibaba.fastjson3.JSONException;
import com.alibaba.fastjson3.ObjectReader;
import com.alibaba.fastjson3.internal.asm.ClassWriter;
import com.alibaba.fastjson3.internal.asm.Label;
import com.alibaba.fastjson3.internal.asm.MethodWriter;
import com.alibaba.fastjson3.internal.asm.Opcodes;
import com.alibaba.fastjson3.util.DynamicClassLoader;

import java.lang.reflect.Constructor;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;
import java.util.concurrent.atomic.AtomicLong;

/**
 * ASM-based ObjectReader creator with DirectField optimization.
 *
 * <h2>DirectField Optimization</h2>
 *
 * <p><b>Problem:</b> Traditional JSON field matching computes hash and does linear search.</p>
 * <p><b>Solution:</b> Use 4-byte field prefix + lookupswitch for O(1) direct field access.</p>
 *
 * <h3>How it works:</h3>
 * <pre>
 * JSON: {"id":123,"name":"test"}
 *       ↑   ↑         ↑
 *       │   │         │
 *    [",i,d,"] [",n,a,m]  <- Read 4 bytes including opening quote
 *
 * Field prefix encoding (big-endian int):
 *   "id"   → 0x22696422  [", i, d, ]
 *   "name" → 0x226e616d  [", n, a, m]
 *
 * Generated bytecode uses lookupswitch for instant dispatch:
 *   lookupswitch(prefix) {
 *       case 0x22696422: → direct write to "id" field
 *       case 0x226e616d: → direct write to "name" field
 *       default: skip unknown field
 *   }
 * </pre>
 *
 * <h3>Field Name Constraints:</h3>
 * <ul>
 *   <li>Minimum: 2 characters → " + name(2) + "</li>
 *   <li>Maximum: 43 characters → name(3) + "</li>
 * </ul>
 *
 * <h3>Performance Benefits:</h3>
 * <ul>
 *   <li>Field matching: O(1) via lookupswitch (vs O(n) linear search)</li>
 *   <li>No hash computation at runtime</li>
 *   <li>Bytecode inline operations (no virtual method calls)</li>
 *   <li>Bypasses reflection overhead</li>
 *   <li>Supports private fields via FieldReader.setXXXValue()</li>
 * </ul>
 *
 * <h3>Supported Types:</h3>
 * <ul>
 *   <li>Primitives: int, long, double, float, boolean, short, byte</li>
 *   <li>Objects: String, Integer, Long, Double, Float, Short, Byte</li>
 *   <li>Arrays: String[], long[]</li>
 * </ul>
 */
@com.alibaba.fastjson3.annotation.JVMOnly
public final class ObjectReaderCreatorASM {
    private static final AtomicLong SEED = new AtomicLong();
    private static final DynamicClassLoader CLASS_LOADER = DynamicClassLoader.getInstance();

    // ASM access flag constants (not defined in Opcodes)
    private static final int ACC_PRIVATE = 0x0002;
    private static final int ACC_PROTECTED = 0x0004;
    private static final int ACC_SYNTHETIC = 0x1000;

    // Stack calculation constants
    private static final int SINGLE_WORD_SIZE = 1;
    private static final int DOUBLE_WORD_SIZE = 2;

    // Debug flag for ASM generation troubleshooting
    private static final boolean DEBUG = Boolean.getBoolean("fastjson.asm.debug");

    private ObjectReaderCreatorASM() {}

    /**
     * Create an ObjectReader using ASM with DirectField optimization.
     * This is the main public API entry point.
     *
     * @param type the target type
     * @return an ASM-generated reader or fallback reflection reader
     */
    @SuppressWarnings("unchecked")
    public static <T> ObjectReader<T> createObjectReader(Class<T> type) {
        // Create fallback reader for non-UTF8 parsers and unsupported types
        ObjectReader<T> fallbackReader = ObjectReaderCreator.createObjectReader(type);

        // Check if class is suitable for ASM generation
        if (!isCandidateForASM(type)) {
            return fallbackReader;
        }

        // Create field readers
        FieldReader[] fieldReaders = createFieldReaders(type);
        if (fieldReaders.length == 0) {
            return fallbackReader;
        }

        // Build field jump info for DirectField
        FieldJumpInfo prefixInfo = buildFieldJumpInfo(fieldReaders, 0, 0);

        // Check if DirectField constraints are met
        if (!prefixInfo.enabled || prefixInfo.prefixes.length == 0) {
            return fallbackReader;
        }

        try {
            return createASMObjectReader(type, fieldReaders, prefixInfo, fallbackReader);
        } catch (Exception e) {
            // If ASM generation fails, fall back to reflection silently
            // Enable debug with: -Dfastjson.asm.debug=true
            if (DEBUG) {
                System.err.println("ASM generation failed for " + type.getName() + ": " + e.getMessage());
                e.printStackTrace();
            }
            return fallbackReader;
        }
    }

    /**
     * Create an ObjectReader using ASM with DirectField optimization.
     * This overload accepts a pre-created fallback reader.
     *
     * @param type the target type
     * @param fallbackReader the reflection reader to use as fallback for non-UTF8 parsers
     */
    @SuppressWarnings("unchecked")
    public static <T> ObjectReader<T> createObjectReader(Class<T> type, ObjectReader<T> fallbackReader) {
        // Check if class is suitable for ASM generation
        if (!isCandidateForASM(type)) {
            return fallbackReader;
        }

        // Create field readers
        FieldReader[] fieldReaders = createFieldReaders(type);
        if (fieldReaders.length == 0) {
            return fallbackReader;
        }

        // Build field jump info for DirectField
        FieldJumpInfo prefixInfo = buildFieldJumpInfo(fieldReaders, 0, 0);


        // Check if DirectField constraints are met
        if (!prefixInfo.enabled || prefixInfo.prefixes.length == 0) {
            return fallbackReader;
        }

        try {
            return createASMObjectReader(type, fieldReaders, prefixInfo, fallbackReader);
        } catch (Exception e) {
            // If ASM generation fails, fall back to reflection silently
            // Enable debug with: -Dfastjson.asm.debug=true
            if (DEBUG) {
                System.err.println("ASM generation failed for " + type.getName() + ": " + e.getMessage());
                e.printStackTrace();
            }
            return fallbackReader;
        }
    }

    /**
     * Check if a class is a candidate for ASM-based reader generation.
     */
    private static boolean isCandidateForASM(Class<?> type) {
        if (type == null) {
            return false;
        }
        // Skip interfaces, arrays, primitives
        if (type.isInterface() || type.isArray() || type.isPrimitive()) {
            return false;
        }
        // Skip JDK classes
        if (type.getClassLoader() == null) {
            return false;
        }
        // Skip non-public classes (inner classes in test classes are often non-public)
        if (!java.lang.reflect.Modifier.isPublic(type.getModifiers())) {
            return false;
        }
        // Skip inner classes (including static nested classes in test classes)
        // to avoid IllegalAccess issues with module system
        if (type.getDeclaringClass() != null) {
            return false;
        }
        return true;
    }

    /**
     * Create FieldReader array for a given class.
     * Reads @JSONField annotation to get the JSON field name.
     */
    private static FieldReader[] createFieldReaders(Class<?> type) {
        java.util.List<FieldReader> readers = new java.util.ArrayList<>();
        for (java.lang.reflect.Field field : type.getDeclaredFields()) {
            int modifiers = field.getModifiers();
            if (java.lang.reflect.Modifier.isStatic(modifiers) ||
                java.lang.reflect.Modifier.isTransient(modifiers)) {
                continue;
            }
            field.setAccessible(true);

            // Read @JSONField annotation for JSON field name
            String jsonFieldName = field.getName();
            String[] alternateNames = null;
            com.alibaba.fastjson3.annotation.JSONField annotation =
                field.getAnnotation(com.alibaba.fastjson3.annotation.JSONField.class);
            if (annotation != null && !annotation.name().isEmpty()) {
                jsonFieldName = annotation.name();
            }
            if (annotation != null && annotation.alternateNames().length > 0) {
                alternateNames = annotation.alternateNames();
            }

            FieldReader reader = new FieldReader(
                jsonFieldName,
                alternateNames,
                field.getGenericType(),
                field.getType(),
                readers.size(),
                null,
                false,
                field,  // Pass the field
                null
            );
            readers.add(reader);
        }
        return readers.toArray(new FieldReader[0]);
    }

    /**
     * Create an ASM-generated ObjectReader using DirectField algorithm.
     */
    @SuppressWarnings("unchecked")
    private static <T> ObjectReader<T> createASMObjectReader(
            Class<T> type,
            FieldReader[] fieldReaders,
            FieldJumpInfo prefixInfo,
            ObjectReader<T> fallbackReader) throws Exception {

        String className = type.getName().replace('.', '/') + "$ASMReader" + SEED.getAndIncrement();
        String superClassName = "java/lang/Object";
        String interfaceName = "com/alibaba/fastjson3/ObjectReader";

        // Type provider for ClassWriter
        java.util.function.Function<String, Class> typeProvider = name -> {
            try {
                return Class.forName(name.replace('/', '.'));
            } catch (ClassNotFoundException e) {
                return null;
            }
        };

        ClassWriter cw = new ClassWriter(typeProvider);
        cw.visit(Opcodes.V1_8,
                Opcodes.ACC_PUBLIC | Opcodes.ACC_FINAL,
                className,
                superClassName,
                new String[]{interfaceName});

        // Add fields
        cw.visitField(Opcodes.ACC_PUBLIC | Opcodes.ACC_FINAL,
                "objectClass",
                "Ljava/lang/Class;");

        // Add fallback reader field
        cw.visitField(ACC_PRIVATE | Opcodes.ACC_FINAL,  // ACC_PRIVATE = 0x0002
                "fallbackReader",
                "Lcom/alibaba/fastjson3/ObjectReader;");

        // Add fieldReaders array to support private fields
        cw.visitField(ACC_PRIVATE | Opcodes.ACC_FINAL,  // ACC_PRIVATE = 0x0002
                "fieldReaders",
                "[Lcom/alibaba/fastjson3/reader/FieldReader;");

        // Add constructor
        MethodWriter ctor = cw.visitMethod(
                Opcodes.ACC_PUBLIC,
                "<init>",
                "(Ljava/lang/Class;Lcom/alibaba/fastjson3/ObjectReader;[Lcom/alibaba/fastjson3/reader/FieldReader;)V",
                64);

        ctor.visitVarInsn(Opcodes.ALOAD, 0);
        ctor.invokespecial("java/lang/Object", "<init>", "()V");
        ctor.visitVarInsn(Opcodes.ALOAD, 0);
        ctor.visitVarInsn(Opcodes.ALOAD, 1);
        ctor.putfield(className, "objectClass", "Ljava/lang/Class;");
        // Store fallbackReader
        ctor.visitVarInsn(Opcodes.ALOAD, 0);
        ctor.visitVarInsn(Opcodes.ALOAD, 2);
        ctor.putfield(className, "fallbackReader", "Lcom/alibaba/fastjson3/ObjectReader;");
        // Store fieldReaders
        ctor.visitVarInsn(Opcodes.ALOAD, 0);
        ctor.visitVarInsn(Opcodes.ALOAD, 3);
        ctor.putfield(className, "fieldReaders", "[Lcom/alibaba/fastjson3/reader/FieldReader;");
        ctor.return_();
        ctor.visitMaxs(4, 4);

        // Add getObjectClass method
        MethodWriter getObjectClass = cw.visitMethod(
                Opcodes.ACC_PUBLIC,
                "getObjectClass",
                "()Ljava/lang/Class;",
                16);

        getObjectClass.visitVarInsn(Opcodes.ALOAD, 0);
        getObjectClass.getfield(className, "objectClass", "Ljava/lang/Class;");
        getObjectClass.areturn();
        getObjectClass.visitMaxs(1, 1);

        // Add readObject method (delegates to readObjectUTF8 for UTF8 path, fallback for others)
        MethodWriter readObject = cw.visitMethod(
                Opcodes.ACC_PUBLIC,
                "readObject",
                "(Lcom/alibaba/fastjson3/JSONParser;Ljava/lang/reflect/Type;Ljava/lang/Object;J)Ljava/lang/Object;",
                64);

        // Check if parser is UTF8
        readObject.visitVarInsn(Opcodes.ALOAD, 1);
        readObject.instanceOf("com/alibaba/fastjson3/JSONParser$UTF8");
        Label notUtf8 = new Label();
        readObject.ifeq(notUtf8);  // jump to notUtf8 if instanceof returns 0 (false)

        // UTF8 path - delegate to readObjectUTF8
        // Stack: this, parser, type, object, long
        // Need: this, utf8_parser, long
        readObject.visitVarInsn(Opcodes.ALOAD, 0);  // this
        readObject.visitVarInsn(Opcodes.ALOAD, 1);  // parser
        readObject.checkcast("com/alibaba/fastjson3/JSONParser$UTF8");  // utf8_parser
        readObject.lload(4);  // long
        readObject.invokevirtual(className, "readObjectUTF8", "(Lcom/alibaba/fastjson3/JSONParser$UTF8;J)Ljava/lang/Object;");
        readObject.areturn();

        // Non-UTF8 path - delegate to fallback reader
        readObject.visitLabel(notUtf8);
        // Stack: this, parser, type, fieldName, long
        readObject.visitVarInsn(Opcodes.ALOAD, 0);  // this
        readObject.getfield(className, "fallbackReader", "Lcom/alibaba/fastjson3/ObjectReader;");
        readObject.visitVarInsn(Opcodes.ALOAD, 1);  // parser
        readObject.visitVarInsn(Opcodes.ALOAD, 2);  // type
        readObject.visitVarInsn(Opcodes.ALOAD, 3);  // fieldName
        readObject.lload(4);  // long
        readObject.invokeinterface("com/alibaba/fastjson3/ObjectReader",
                "readObject",
                "(Lcom/alibaba/fastjson3/JSONParser;Ljava/lang/reflect/Type;Ljava/lang/Object;J)Ljava/lang/Object;");
        readObject.areturn();
        readObject.visitMaxs(6, 6);

        // Generate readObjectUTF8 with DirectField
        generateDirectReadUTF8(cw, className, type, fieldReaders, prefixInfo);

        byte[] bytecode = cw.toByteArray();

        Class<?> generatedClass = CLASS_LOADER.loadClass(
                className.replace('/', '.'),
                bytecode,
                0,
                bytecode.length);
        Constructor<?> constructor = generatedClass.getConstructor(
                Class.class,
                ObjectReader.class,
                FieldReader[].class);
        return (ObjectReader<T>) constructor.newInstance(type, fallbackReader, fieldReaders);
    }

    // ==================== Field Jump Info ====================

    /**
     * Groups fields by their 4-byte prefix for O(1) direct access.
     *
     * <p>Each group contains fields that share the same 4-byte prefix.
     * Used to generate lookupswitch bytecode for instant field matching.</p>
     */
    static class FieldJumpInfo {
        /** 4-byte prefixes sorted for binary search */
        public final int[] prefixes;

        /** Number of fields in each prefix group */
        public final int[] prefixCounts;

        /** Fields in each prefix group (may have multiple fields with same prefix) */
        public final List<List<JumpField>> fields;

        /** True if direct field optimization is enabled for this class */
        public final boolean enabled;

        public FieldJumpInfo(int[] prefixes, int[] prefixCounts,
                             List<List<JumpField>> fields, boolean enabled) {
            this.prefixes = prefixes;
            this.prefixCounts = prefixCounts;
            this.fields = fields;
            this.enabled = enabled;
        }
    }

    /**
     * A field that has been matched by its prefix.
     *
     * <p>Used during bytecode generation to emit field-specific code.</p>
     */
    static class JumpField {
        /** Index in the original fieldReaders array */
        public final int index;

        /** The field name (e.g., "id", "name") */
        public final String fieldName;

        /** Length of the field name in characters */
        public final int nameLength;

        public JumpField(int index, String fieldName, int nameLength) {
            this.index = index;
            this.fieldName = fieldName;
            this.nameLength = nameLength;
        }
    }

    /**
     * Check if a string contains only ASCII characters.
     * DirectField optimization only works with ASCII field names.
     *
     * @param str the string to check
     * @return true if all characters are ASCII (<= 127)
     */
    private static boolean isAscii(String str) {
        for (int i = 0; i < str.length(); i++) {
            if (str.charAt(i) > 127) {
                return false;
            }
        }
        return true;
    }

    /**
     * Compute 4-byte prefix for a field name in JSON format.
     *
     * <p>Examples:</p>
     * <pre>
     * "id"   → [", i, d, ]     → 0x22696422
     * "name" → [", n, a, m]     → 0x226e616d
     * </pre>
     *
     * @param fieldName the field name without quotes
     * @return 4-byte prefix as int (big-endian), or 0 if invalid length
     */
    public static int computeFieldNamePrefix(String fieldName) {
        int len = fieldName.length();
        if (len < 2 || len > 43) {
            return 0;
        }

        byte[] nameBytes = fieldName.getBytes(StandardCharsets.UTF_8);
        byte[] prefixBytes = new byte[4];
        prefixBytes[0] = '"';

        if (nameBytes.length == 2) {
            System.arraycopy(nameBytes, 0, prefixBytes, 1, 2);
            prefixBytes[3] = '"';
        } else {
            System.arraycopy(nameBytes, 0, prefixBytes, 1, Math.min(3, nameBytes.length));
        }

        return ((prefixBytes[0] & 0xFF) << 24)
             | ((prefixBytes[1] & 0xFF) << 16)
             | ((prefixBytes[2] & 0xFF) << 8)
             | (prefixBytes[3] & 0xFF);
    }

    /**
     * Check if a field type is supported by DirectField optimization.
     *
     * @param fieldClass the field type to check
     * @return true if the type is supported
     */
    private static boolean isSupportedFieldType(Class<?> fieldClass) {
        // Supported types: primitives and their wrappers, String, and specific arrays
        return fieldClass == String.class
                || fieldClass == int.class || fieldClass == Integer.class
                || fieldClass == long.class || fieldClass == Long.class
                || fieldClass == boolean.class || fieldClass == Boolean.class
                || fieldClass == double.class || fieldClass == Double.class
                || fieldClass == float.class || fieldClass == Float.class
                || fieldClass == short.class || fieldClass == Short.class
                || fieldClass == byte.class || fieldClass == Byte.class
                || fieldClass == String[].class
                || fieldClass == long[].class;
    }

    /**
     * Check if all field types are supported by DirectField optimization.
     *
     * @param fieldReaders array of field readers
     * @return true if all field types are supported
     */
    private static boolean allFieldsSupported(FieldReader[] fieldReaders) {
        for (FieldReader fr : fieldReaders) {
            if (!isSupportedFieldType(fr.fieldClass)) {
                return false;
            }
        }
        return true;
    }

    /**
     * Build prefix group information for DirectField algorithm.
     *
     * @param fieldReaders array of field readers
     * @param minNameLen minimum field name length
     * @param maxNameLen maximum field name length
     * @return FieldJumpInfo
     */
    public static FieldJumpInfo buildFieldJumpInfo(FieldReader[] fieldReaders,
                                                      int minNameLen, int maxNameLen) {
        int actualMinLen = Integer.MAX_VALUE;
        int actualMaxLen = Integer.MIN_VALUE;

        for (FieldReader fr : fieldReaders) {
            int len = fr.fieldName.length();
            actualMinLen = Math.min(actualMinLen, len);
            actualMaxLen = Math.max(actualMaxLen, len);

            // Check for non-ASCII characters in field name
            // DirectField only works with ASCII field names due to multi-byte UTF-8 encoding
            if (!isAscii(fr.fieldName)) {
                return new FieldJumpInfo(new int[0], new int[0], new ArrayList<>(), false);
            }

            for (String alt : fr.alternateNames) {
                int altLen = alt.length();
                actualMinLen = Math.min(actualMinLen, altLen);
                actualMaxLen = Math.max(actualMaxLen, altLen);

                // Check for non-ASCII in alternate names
                if (!isAscii(alt)) {
                    return new FieldJumpInfo(new int[0], new int[0], new ArrayList<>(), false);
                }
            }
        }

        if (minNameLen == 0) minNameLen = actualMinLen;
        if (maxNameLen == 0) maxNameLen = actualMaxLen;

        // DirectField requires: 2 <= length <= 43
        if (minNameLen < 2 || maxNameLen > 43) {
            return new FieldJumpInfo(new int[0], new int[0], new ArrayList<>(), false);
        }

        // Check if all field types are supported
        if (!allFieldsSupported(fieldReaders)) {
            return new FieldJumpInfo(new int[0], new int[0], new ArrayList<>(), false);
        }

        TreeMap<Integer, List<JumpField>> prefixMap = new TreeMap<>();

        for (int i = 0; i < fieldReaders.length; i++) {
            FieldReader fr = fieldReaders[i];
            addFieldToPrefixMap(prefixMap, fr, i, fr.fieldName);
            for (String alt : fr.alternateNames) {
                addFieldToPrefixMap(prefixMap, fr, i, alt);
            }
        }

        if (prefixMap.isEmpty()) {
            return new FieldJumpInfo(new int[0], new int[0], new ArrayList<>(), false);
        }

        // Check for prefix collisions (multiple fields with same 4-byte prefix)
        // When collisions exist, disable DirectField to avoid incorrect parsing
        for (var entry : prefixMap.entrySet()) {
            if (entry.getValue().size() > 1) {
                // Prefix collision detected - disable DirectField for safety
                return new FieldJumpInfo(new int[0], new int[0], new ArrayList<>(), false);
            }
        }

        int[] prefixes = new int[prefixMap.size()];
        int[] prefixCounts = new int[prefixMap.size()];
        List<List<JumpField>> fields = new ArrayList<>(prefixMap.size());

        int idx = 0;
        for (var entry : prefixMap.entrySet()) {
            prefixes[idx] = entry.getKey();
            prefixCounts[idx] = entry.getValue().size();
            fields.add(entry.getValue());
            idx++;
        }

        return new FieldJumpInfo(prefixes, prefixCounts, fields, true);
    }

    /**
     * Add a field to the prefix map.
     */
    private static void addFieldToPrefixMap(TreeMap<Integer, List<JumpField>> prefixMap,
                                          FieldReader fr, int index, String fieldName) {
        int prefix = computeFieldNamePrefix(fieldName);
        if (prefix == 0) {
            return;
        }
        prefixMap.computeIfAbsent(prefix, k -> new ArrayList<>())
                .add(new JumpField(index, fieldName, fieldName.length()));
    }

    /**
     * Print field jump info for debugging.
     * Requires -Dfastjson.asm.debug=true to enable.
     */
    public static void printFieldJumpInfo(FieldJumpInfo info) {
        if (!DEBUG) {
            return;
        }
        System.out.println("=== DirectField Prefix Group Info ===");
        System.out.println("Enabled: " + info.enabled);
        System.out.println("Prefix groups: " + info.prefixes.length);

        for (int i = 0; i < info.prefixes.length; i++) {
            System.out.printf("  Group %d: prefix=0x%08X, count=%d\n",
                i, info.prefixes[i], info.prefixCounts[i]);
            for (JumpField pf : info.fields.get(i)) {
                System.out.printf("    - [%d] %s (len=%d)\n",
                    pf.index, pf.fieldName, pf.nameLength);
            }
        }
    }

    // ==================== ASM Bytecode Generation ====================

    /**
     * Create a fully functional ASM reader with DirectField algorithm.
     * This is a public API for testing that creates its own fallback reader.
     */
    @SuppressWarnings("unchecked")
    public static <T> ObjectReader<T> createDirectFieldReader(Class<T> type) {
        // Create fallback reader for non-UTF8 parsers
        ObjectReader<T> fallbackReader = ObjectReaderCreator.createObjectReader(type);

        // Create field readers
        FieldReader[] fieldReaders = createFieldReaders(type);
        if (fieldReaders.length == 0) {
            return fallbackReader;
        }

        // Build prefix group info
        FieldJumpInfo prefixInfo = buildFieldJumpInfo(fieldReaders, 0, 0);
        if (!prefixInfo.enabled || prefixInfo.prefixes.length == 0) {
            return fallbackReader;
        }

        try {
            return createASMObjectReader(type, fieldReaders, prefixInfo, fallbackReader);
        } catch (Exception e) {
            if (DEBUG) {
                System.err.println("ASM generation failed for " + type.getName() + ": " + e.getMessage());
                e.printStackTrace();
            }
            return fallbackReader;
        }
    }

    /**
     * Generate the readObjectUTF8 method with DirectField algorithm.
     *
     * <p>Uses lookupswitch for O(1) field prefix dispatch.</p>
     */
    private static void generateDirectReadUTF8(
            ClassWriter cw,
            String className,
            Class<?> type,
            FieldReader[] fieldReaders,
            FieldJumpInfo prefixInfo) {

        MethodWriter mv = cw.visitMethod(
                Opcodes.ACC_PUBLIC,
                "readObjectUTF8",
                "(Lcom/alibaba/fastjson3/JSONParser$UTF8;J)Ljava/lang/Object;",
                512);

        // Local variable indices
        final int VAR_UTF8 = 1;
        // Note: long at slot 2 uses slots 2 and 3
        final int VAR_INSTANCE = 4;
        final int VAR_TEMP = 5;

        // Labels
        Label labelNotNull = new Label();
        Label labelCheckBrace = new Label();
        Label labelLoopStart = new Label();
        Label labelLoopEnd = new Label();
        Label labelReturnInstance = new Label();
        Label labelNextField = new Label();
        Label labelSwitchDefault = new Label();
        Label labelSkipComma = new Label();

        // Create labels for each prefix group
        Label[] prefixLabels = new Label[prefixInfo.prefixes.length];
        for (int i = 0; i < prefixInfo.prefixes.length; i++) {
            prefixLabels[i] = new Label();
        }

        // Initialize instance to null
        mv.aconst_null();
        mv.visitVarInsn(Opcodes.ASTORE, VAR_INSTANCE);

        // === Check for null ===
        mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
        mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                "skipWSAndPeek",
                "()I");
        mv.visitVarInsn(Opcodes.ISTORE, VAR_TEMP);

        mv.visitVarInsn(Opcodes.ILOAD, VAR_TEMP);
        mv.bipush('n');
        mv.if_icmpne(labelNotNull);

        mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
        mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                "readNull",
                "()Z");
        mv.ifne(labelReturnInstance);

        mv.visitLabel(labelNotNull);

        // === Verify opening brace ===
        mv.visitVarInsn(Opcodes.ILOAD, VAR_TEMP);
        mv.bipush('{');
        mv.if_icmpeq(labelCheckBrace);

        // Throw exception if not '{'
        mv.new_("com/alibaba/fastjson3/JSONException");
        mv.dup();
        mv.visitLdcInsn("expected '{'");
        mv.invokespecial("com/alibaba/fastjson3/JSONException",
                "<init>",
                "(Ljava/lang/String;)V");
        mv.athrow();

        mv.visitLabel(labelCheckBrace);

        // === Skip '{' ===
        mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
        mv.iconst_1();
        mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                "advance",
                "(I)V");

        // === Create instance ===
        mv.new_(type.getName().replace('.', '/'));
        mv.dup();
        mv.invokespecial(type.getName().replace('.', '/'), "<init>", "()V");
        mv.visitVarInsn(Opcodes.ASTORE, VAR_INSTANCE);

        // === Check if empty object ===
        mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
        mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                "skipWSAndPeek",
                "()I");
        mv.visitVarInsn(Opcodes.ISTORE, VAR_TEMP);

        mv.visitVarInsn(Opcodes.ILOAD, VAR_TEMP);
        mv.bipush('}');
        mv.if_icmpne(labelLoopStart);

        // Empty object - skip '}' and return
        mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
        mv.iconst_1();
        mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                "advance",
                "(I)V");
        mv.goto_(labelReturnInstance);

        // === Field reading loop ===
        mv.visitLabel(labelLoopStart);

        // Get current offset for readInt4
        mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
        mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                "getOffset",
                "()I");
        mv.visitVarInsn(Opcodes.ISTORE, VAR_TEMP);

        // Read 4-byte prefix
        mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
        mv.visitVarInsn(Opcodes.ILOAD, VAR_TEMP);
        mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                "readInt4",
                "(I)I");

        // lookupswitch on prefix - pop the result directly
        mv.visitLookupSwitchInsn(labelSwitchDefault, prefixInfo.prefixes, prefixLabels);

        // === Generate code for each prefix group ===
        for (int i = 0; i < prefixInfo.prefixes.length; i++) {
            mv.visitLabel(prefixLabels[i]);

            List<JumpField> fieldsInGroup = prefixInfo.fields.get(i);
            if (fieldsInGroup.size() == 1) {
                JumpField pf = fieldsInGroup.get(0);
                FieldReader fr = fieldReaders[pf.index];
                int fieldNameLen = pf.nameLength;

                // After prefix match, we need to skip to the value
                // Current position is at the opening quote of the field name
                // We need to advance past: opening quote + field name + closing quote + colon
                // The prefix was read from this position, so we need to advance fieldNameLen + 2 bytes
                // (for the opening and closing quotes) + 1 byte for the colon

                int skipCount = fieldNameLen + 2 + 1; // '"', name, '"', ':'

                mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
                mv.visitLdcInsn(skipCount);
                mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                        "advance",
                        "(I)V");

                // Read field value based on type
                Class<?> fieldClass = fr.fieldClass;
                if (fieldClass == String.class) {
                    // Read String value
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
                    mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                            "readString",
                            "()Ljava/lang/String;");
                    // Store in temp
                    mv.visitVarInsn(Opcodes.ASTORE, VAR_TEMP);

                    // Call fieldReader.setObjectValue(instance, value)
                    mv.visitVarInsn(Opcodes.ALOAD, 0);  // this
                    mv.getfield(className, "fieldReaders", "[Lcom/alibaba/fastjson3/reader/FieldReader;");
                    mv.visitLdcInsn(pf.index);
                    mv.aaload();  // Stack: fieldReader
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_INSTANCE);  // instance
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_TEMP);  // value
                    mv.invokevirtual("com/alibaba/fastjson3/reader/FieldReader",
                            "setObjectValue",
                            "(Ljava/lang/Object;Ljava/lang/Object;)V");
                } else if (fieldClass == int.class) {
                    // Read int value
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
                    mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                            "readInt",
                            "()I");
                    // Store in temp
                    mv.visitVarInsn(Opcodes.ISTORE, VAR_TEMP);

                    // Call fieldReader.setIntValue(instance, value)
                    mv.visitVarInsn(Opcodes.ALOAD, 0);  // this
                    mv.getfield(className, "fieldReaders", "[Lcom/alibaba/fastjson3/reader/FieldReader;");
                    mv.visitLdcInsn(pf.index);
                    mv.aaload();  // Stack: fieldReader
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_INSTANCE);  // instance
                    mv.visitVarInsn(Opcodes.ILOAD, VAR_TEMP);  // value
                    mv.invokevirtual("com/alibaba/fastjson3/reader/FieldReader",
                            "setIntValue",
                            "(Ljava/lang/Object;I)V");
                } else if (fieldClass == Integer.class) {
                    // Read Integer value
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
                    mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                            "readInt",
                            "()I");
                    // Store in temp
                    mv.visitVarInsn(Opcodes.ISTORE, VAR_TEMP);
                    // Call fieldReader.setObjectValue with boxed value
                    mv.visitVarInsn(Opcodes.ALOAD, 0);  // this
                    mv.getfield(className, "fieldReaders", "[Lcom/alibaba/fastjson3/reader/FieldReader;");
                    mv.visitLdcInsn(pf.index);
                    mv.aaload();
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_INSTANCE);
                    mv.visitVarInsn(Opcodes.ILOAD, VAR_TEMP);
                    mv.invokestatic("java/lang/Integer", "valueOf", "(I)Ljava/lang/Integer;");
                    mv.invokevirtual("com/alibaba/fastjson3/reader/FieldReader",
                            "setObjectValue",
                            "(Ljava/lang/Object;Ljava/lang/Object;)V");
                } else if (fieldClass == long.class) {
                    // Read long value
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
                    mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                            "readLong",
                            "()J");
                    // Store in temp (long uses 2 slots)
                    mv.visitVarInsn(Opcodes.LSTORE, VAR_TEMP);
                    // Call fieldReader.setLongValue(instance, value)
                    mv.visitVarInsn(Opcodes.ALOAD, 0);  // this
                    mv.getfield(className, "fieldReaders", "[Lcom/alibaba/fastjson3/reader/FieldReader;");
                    mv.visitLdcInsn(pf.index);
                    mv.aaload();
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_INSTANCE);
                    mv.visitVarInsn(Opcodes.LLOAD, VAR_TEMP);
                    mv.invokevirtual("com/alibaba/fastjson3/reader/FieldReader",
                            "setLongValue",
                            "(Ljava/lang/Object;J)V");
                } else if (fieldClass == Long.class) {
                    // Read Long value
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
                    mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                            "readLong",
                            "()J");
                    // Store in temp (long uses 2 slots)
                    mv.visitVarInsn(Opcodes.LSTORE, VAR_TEMP);
                    // Call fieldReader.setObjectValue with boxed value
                    mv.visitVarInsn(Opcodes.ALOAD, 0);  // this
                    mv.getfield(className, "fieldReaders", "[Lcom/alibaba/fastjson3/reader/FieldReader;");
                    mv.visitLdcInsn(pf.index);
                    mv.aaload();
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_INSTANCE);
                    mv.visitVarInsn(Opcodes.LLOAD, VAR_TEMP);
                    mv.invokestatic("java/lang/Long", "valueOf", "(J)Ljava/lang/Long;");
                    mv.invokevirtual("com/alibaba/fastjson3/reader/FieldReader",
                            "setObjectValue",
                            "(Ljava/lang/Object;Ljava/lang/Object;)V");
                } else if (fieldClass == boolean.class) {
                    // Read boolean value
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
                    mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                            "readBoolean",
                            "()Z");
                    // Store in temp
                    mv.visitVarInsn(Opcodes.ISTORE, VAR_TEMP);
                    // Call fieldReader.setBooleanValue(instance, value)
                    mv.visitVarInsn(Opcodes.ALOAD, 0);  // this
                    mv.getfield(className, "fieldReaders", "[Lcom/alibaba/fastjson3/reader/FieldReader;");
                    mv.visitLdcInsn(pf.index);
                    mv.aaload();
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_INSTANCE);
                    mv.visitVarInsn(Opcodes.ILOAD, VAR_TEMP);
                    mv.invokevirtual("com/alibaba/fastjson3/reader/FieldReader",
                            "setBooleanValue",
                            "(Ljava/lang/Object;Z)V");
                } else if (fieldClass == double.class) {
                    // Read double value
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
                    mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                            "readDouble",
                            "()D");
                    // Store in temp var (use VAR_TEMP and VAR_TEMP+1 for double)
                    mv.visitVarInsn(Opcodes.DSTORE, VAR_TEMP);
                    // Call fieldReader.setDoubleValue(instance, value)
                    mv.visitVarInsn(Opcodes.ALOAD, 0);  // this
                    mv.getfield(className, "fieldReaders", "[Lcom/alibaba/fastjson3/reader/FieldReader;");
                    mv.visitLdcInsn(pf.index);
                    mv.aaload();
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_INSTANCE);
                    mv.visitVarInsn(Opcodes.DLOAD, VAR_TEMP);
                    mv.invokevirtual("com/alibaba/fastjson3/reader/FieldReader",
                            "setDoubleValue",
                            "(Ljava/lang/Object;D)V");
                } else if (fieldClass == Double.class) {
                    // Read Double value
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
                    mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                            "readDouble",
                            "()D");
                    // Store in temp var
                    mv.visitVarInsn(Opcodes.DSTORE, VAR_TEMP);
                    // Load fieldReader and instance, then box the double
                    mv.visitVarInsn(Opcodes.ALOAD, 0);  // this
                    mv.getfield(className, "fieldReaders", "[Lcom/alibaba/fastjson3/reader/FieldReader;");
                    mv.visitLdcInsn(pf.index);
                    mv.aaload();
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_INSTANCE);
                    mv.visitVarInsn(Opcodes.DLOAD, VAR_TEMP);
                    mv.invokestatic("java/lang/Double", "valueOf", "(D)Ljava/lang/Double;");
                    mv.invokevirtual("com/alibaba/fastjson3/reader/FieldReader",
                            "setObjectValue",
                            "(Ljava/lang/Object;Ljava/lang/Object;)V");
                } else if (fieldClass == float.class) {
                    // Read float value (cast from double)
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
                    mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                            "readDouble",
                            "()D");
                    mv.d2f();
                    // Store in temp
                    mv.visitVarInsn(Opcodes.ISTORE, VAR_TEMP);
                    // Load as float and call setObjectValue
                    mv.visitVarInsn(Opcodes.ALOAD, 0);  // this
                    mv.getfield(className, "fieldReaders", "[Lcom/alibaba/fastjson3/reader/FieldReader;");
                    mv.visitLdcInsn(pf.index);
                    mv.aaload();
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_INSTANCE);
                    mv.visitVarInsn(Opcodes.ILOAD, VAR_TEMP);
                    mv.invokestatic("java/lang/Float", "valueOf", "(F)Ljava/lang/Float;");
                    mv.invokevirtual("com/alibaba/fastjson3/reader/FieldReader",
                            "setObjectValue",
                            "(Ljava/lang/Object;Ljava/lang/Object;)V");
                } else if (fieldClass == Float.class) {
                    // Read Float value (cast from double)
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
                    mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                            "readDouble",
                            "()D");
                    mv.d2f();
                    // Store in temp
                    mv.visitVarInsn(Opcodes.ISTORE, VAR_TEMP);
                    // Load as float and call setObjectValue
                    mv.visitVarInsn(Opcodes.ALOAD, 0);  // this
                    mv.getfield(className, "fieldReaders", "[Lcom/alibaba/fastjson3/reader/FieldReader;");
                    mv.visitLdcInsn(pf.index);
                    mv.aaload();
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_INSTANCE);
                    mv.visitVarInsn(Opcodes.ILOAD, VAR_TEMP);
                    mv.invokestatic("java/lang/Float", "valueOf", "(F)Ljava/lang/Float;");
                    mv.invokevirtual("com/alibaba/fastjson3/reader/FieldReader",
                            "setObjectValue",
                            "(Ljava/lang/Object;Ljava/lang/Object;)V");
                } else if (fieldClass == short.class) {
                    // Read short value (cast from int)
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
                    mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                            "readInt",
                            "()I");
                    mv.i2s();
                    // Store in temp
                    mv.visitVarInsn(Opcodes.ISTORE, VAR_TEMP);
                    // Load as int and call setObjectValue
                    mv.visitVarInsn(Opcodes.ALOAD, 0);  // this
                    mv.getfield(className, "fieldReaders", "[Lcom/alibaba/fastjson3/reader/FieldReader;");
                    mv.visitLdcInsn(pf.index);
                    mv.aaload();
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_INSTANCE);
                    mv.visitVarInsn(Opcodes.ILOAD, VAR_TEMP);
                    mv.invokestatic("java/lang/Short", "valueOf", "(S)Ljava/lang/Short;");
                    mv.invokevirtual("com/alibaba/fastjson3/reader/FieldReader",
                            "setObjectValue",
                            "(Ljava/lang/Object;Ljava/lang/Object;)V");
                } else if (fieldClass == Short.class) {
                    // Read Short value (cast from int)
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
                    mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                            "readInt",
                            "()I");
                    mv.i2s();
                    // Store in temp
                    mv.visitVarInsn(Opcodes.ISTORE, VAR_TEMP);
                    // Load as int and call setObjectValue
                    mv.visitVarInsn(Opcodes.ALOAD, 0);  // this
                    mv.getfield(className, "fieldReaders", "[Lcom/alibaba/fastjson3/reader/FieldReader;");
                    mv.visitLdcInsn(pf.index);
                    mv.aaload();
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_INSTANCE);
                    mv.visitVarInsn(Opcodes.ILOAD, VAR_TEMP);
                    mv.invokestatic("java/lang/Short", "valueOf", "(S)Ljava/lang/Short;");
                    mv.invokevirtual("com/alibaba/fastjson3/reader/FieldReader",
                            "setObjectValue",
                            "(Ljava/lang/Object;Ljava/lang/Object;)V");
                } else if (fieldClass == byte.class) {
                    // Read byte value (cast from int)
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
                    mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                            "readInt",
                            "()I");
                    mv.i2b();
                    // Store in temp
                    mv.visitVarInsn(Opcodes.ISTORE, VAR_TEMP);
                    // Load as int and call setObjectValue
                    mv.visitVarInsn(Opcodes.ALOAD, 0);  // this
                    mv.getfield(className, "fieldReaders", "[Lcom/alibaba/fastjson3/reader/FieldReader;");
                    mv.visitLdcInsn(pf.index);
                    mv.aaload();
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_INSTANCE);
                    mv.visitVarInsn(Opcodes.ILOAD, VAR_TEMP);
                    mv.invokestatic("java/lang/Byte", "valueOf", "(B)Ljava/lang/Byte;");
                    mv.invokevirtual("com/alibaba/fastjson3/reader/FieldReader",
                            "setObjectValue",
                            "(Ljava/lang/Object;Ljava/lang/Object;)V");
                } else if (fieldClass == Byte.class) {
                    // Read Byte value (cast from int)
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
                    mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                            "readInt",
                            "()I");
                    mv.i2b();
                    // Store in temp
                    mv.visitVarInsn(Opcodes.ISTORE, VAR_TEMP);
                    // Load as int and call setObjectValue
                    mv.visitVarInsn(Opcodes.ALOAD, 0);  // this
                    mv.getfield(className, "fieldReaders", "[Lcom/alibaba/fastjson3/reader/FieldReader;");
                    mv.visitLdcInsn(pf.index);
                    mv.aaload();
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_INSTANCE);
                    mv.visitVarInsn(Opcodes.ILOAD, VAR_TEMP);
                    mv.invokestatic("java/lang/Byte", "valueOf", "(B)Ljava/lang/Byte;");
                    mv.invokevirtual("com/alibaba/fastjson3/reader/FieldReader",
                            "setObjectValue",
                            "(Ljava/lang/Object;Ljava/lang/Object;)V");
                } else if (fieldClass == String[].class) {
                    // Read String[] value
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
                    mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                            "readStringArrayInline",
                            "()[Ljava/lang/String;");
                    // Store in temp
                    mv.visitVarInsn(Opcodes.ASTORE, VAR_TEMP);
                    // Call fieldReader.setObjectValue
                    mv.visitVarInsn(Opcodes.ALOAD, 0);  // this
                    mv.getfield(className, "fieldReaders", "[Lcom/alibaba/fastjson3/reader/FieldReader;");
                    mv.visitLdcInsn(pf.index);
                    mv.aaload();
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_INSTANCE);
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_TEMP);
                    mv.invokevirtual("com/alibaba/fastjson3/reader/FieldReader",
                            "setObjectValue",
                            "(Ljava/lang/Object;Ljava/lang/Object;)V");
                } else if (fieldClass == long[].class) {
                    // Read long[] value
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
                    mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                            "readLongArrayInline",
                            "()[J");
                    // Store in temp
                    mv.visitVarInsn(Opcodes.ASTORE, VAR_TEMP);
                    // Call fieldReader.setObjectValue
                    mv.visitVarInsn(Opcodes.ALOAD, 0);  // this
                    mv.getfield(className, "fieldReaders", "[Lcom/alibaba/fastjson3/reader/FieldReader;");
                    mv.visitLdcInsn(pf.index);
                    mv.aaload();
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_INSTANCE);
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_TEMP);
                    mv.invokevirtual("com/alibaba/fastjson3/reader/FieldReader",
                            "setObjectValue",
                            "(Ljava/lang/Object;Ljava/lang/Object;)V");
                } else {
                    // For other types, skip the value for now
                    mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
                    mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                            "skipValue",
                            "()V");
                }
            } else {
                // Multiple fields with same prefix - skip for now
                mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
                mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                        "skipValue",
                        "()V");
            }
            // Always jump to next field
            mv.goto_(labelNextField);
        }

        // === Switch default - unknown field, skip it ===
        mv.visitLabel(labelSwitchDefault);
        mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
        mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                "skipValue",
                "()V");

        // === Next field handling ===
        mv.visitLabel(labelNextField);

        // Skip whitespace and check for '}' or ','
        mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
        mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                "skipWSAndPeek",
                "()I");
        mv.visitVarInsn(Opcodes.ISTORE, VAR_TEMP);

        mv.visitVarInsn(Opcodes.ILOAD, VAR_TEMP);
        mv.bipush('}');
        mv.if_icmpeq(labelLoopEnd);

        mv.visitVarInsn(Opcodes.ILOAD, VAR_TEMP);
        mv.bipush(',');
        mv.if_icmpeq(labelSkipComma);

        // Unexpected character - exit loop
        mv.goto_(labelLoopEnd);

        mv.visitLabel(labelSkipComma);
        mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
        mv.iconst_1();
        mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                "advance",
                "(I)V");
        mv.goto_(labelLoopStart);

        mv.visitLabel(labelLoopEnd);
        // Skip closing '}'
        mv.visitVarInsn(Opcodes.ALOAD, VAR_UTF8);
        mv.iconst_1();
        mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                "advance",
                "(I)V");

        mv.visitLabel(labelReturnInstance);
        mv.visitVarInsn(Opcodes.ALOAD, VAR_INSTANCE);
        mv.areturn();

        mv.visitMaxs(3, 6);
    }

    /**
     * Generate field handler code.
     * For now, this is a simple stub that skips the field value.
     * TODO: Implement proper field value reading based on field type.
     */
    private static void generateFieldHandler(
            MethodWriter mv,
            String className,
            Class<?> type,
            FieldReader fieldReader,
            int varUtf8,
            int varInstance,
            Label labelNextField,
            Label labelLoopEnd) {

        // For now, just skip the value to get the basic structure working
        // Skip to ':' first
        mv.visitVarInsn(Opcodes.ALOAD, varUtf8);
        mv.invokevirtual("com/alibaba/fastjson3/JSONParser$UTF8",
                "skipValue",
                "()V");

        mv.goto_(labelNextField);
    }

    /**
     * Test method to verify basic ASM generation works.
     * Creates a simple ObjectReader stub.
     */
    @SuppressWarnings("unchecked")
    public static <T> ObjectReader<T> createTestASMReader(Class<T> type) {
        String className = type.getName().replace('.', '/') + "$ASMReader" + SEED.getAndIncrement();
        String superClassName = "java/lang/Object";
        String interfaceName = "com/alibaba/fastjson3/ObjectReader";

        // Type provider for ClassWriter
        java.util.function.Function<String, Class> typeProvider = name -> {
            try {
                return Class.forName(name.replace('/', '.'));
            } catch (ClassNotFoundException e) {
                return null;
            }
        };

        ClassWriter cw = new ClassWriter(typeProvider);
        cw.visit(Opcodes.V1_8,
                Opcodes.ACC_PUBLIC | Opcodes.ACC_FINAL,
                className,
                superClassName,
                new String[]{interfaceName});

        // Add objectClass field
        cw.visitField(Opcodes.ACC_PUBLIC | Opcodes.ACC_FINAL,
                "objectClass",
                "Ljava/lang/Class;");

        // Add constructor
        MethodWriter ctor = cw.visitMethod(
                Opcodes.ACC_PUBLIC,
                "<init>",
                "(Ljava/lang/Class;)V",
                64);

        // Call super constructor (Object)
        ctor.visitVarInsn(Opcodes.ALOAD, 0); // this
        ctor.invokespecial("java/lang/Object", "<init>", "()V");

        // Store objectClass field
        ctor.visitVarInsn(Opcodes.ALOAD, 0);
        ctor.visitVarInsn(Opcodes.ALOAD, 1);
        ctor.putfield(className, "objectClass", "Ljava/lang/Class;");

        ctor.return_();
        ctor.visitMaxs(2, 2);

        // Add getObjectClass method
        MethodWriter getObjectClass = cw.visitMethod(
                Opcodes.ACC_PUBLIC,
                "getObjectClass",
                "()Ljava/lang/Class;",
                16);

        getObjectClass.visitVarInsn(Opcodes.ALOAD, 0);
        getObjectClass.getfield(className, "objectClass", "Ljava/lang/Class;");
        getObjectClass.areturn();
        getObjectClass.visitMaxs(1, 1);

        // Add readObject method
        MethodWriter readObject = cw.visitMethod(
                Opcodes.ACC_PUBLIC,
                "readObject",
                "(Lcom/alibaba/fastjson3/JSONParser;Ljava/lang/reflect/Type;Ljava/lang/Object;J)Ljava/lang/Object;",
                64);

        // Check if parser is UTF8
        readObject.visitVarInsn(Opcodes.ALOAD, 1);
        readObject.instanceOf("com/alibaba/fastjson3/JSONParser$UTF8");
        Label notUtf8 = new Label();
        readObject.ifeq(notUtf8);  // jump to notUtf8 if instanceof returns 0 (false)

        // UTF8 path - delegate to readObjectUTF8
        readObject.visitVarInsn(Opcodes.ALOAD, 0);
        readObject.visitVarInsn(Opcodes.ALOAD, 1);
        readObject.visitVarInsn(Opcodes.ALOAD, 1);
        readObject.checkcast("com/alibaba/fastjson3/JSONParser$UTF8");
        readObject.lload(4);
        readObject.invokevirtual(className, "readObjectUTF8", "(Lcom/alibaba/fastjson3/JSONParser$UTF8;J)Ljava/lang/Object;");
        readObject.areturn();

        // Non-UTF8 path - return null
        readObject.visitLabel(notUtf8);
        readObject.aconst_null();
        readObject.areturn();
        readObject.visitMaxs(3, 6);

        // Add readObjectUTF8 method (stub for now)
        MethodWriter readObjectUTF8 = cw.visitMethod(
                Opcodes.ACC_PUBLIC,
                "readObjectUTF8",
                "(Lcom/alibaba/fastjson3/JSONParser$UTF8;J)Ljava/lang/Object;",
                64);

        // Just return null for now - this is a stub
        readObjectUTF8.aconst_null();
        readObjectUTF8.areturn();
        readObjectUTF8.visitMaxs(1, 4);

        byte[] bytecode = cw.toByteArray();

        try {
            Class<?> generatedClass = CLASS_LOADER.loadClass(
                    className.replace('/', '.'),
                    bytecode,
                    0,
                    bytecode.length);
            Constructor<?> constructor = generatedClass.getConstructor(Class.class);
            return (ObjectReader<T>) constructor.newInstance(type);
        } catch (Exception e) {
            throw new JSONException("Failed to create ASM reader for " + type.getName(), e);
        }
    }
}
