package com.alibaba.fastjson3.util;

import java.lang.ref.Reference;
import java.lang.ref.ReferenceQueue;
import java.lang.ref.WeakReference;
import java.util.Collections;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * ClassLoader for loading ASM-generated bytecode at runtime.
 *
 * <p>Each instance maintains its own set of generated classes via weak references.
 * When a generated class is no longer referenced elsewhere, the weak reference is
 * cleared and the map entry is removed via the reference queue.</p>
 *
 * <p><b>ClassLoader lifecycle:</b> For the ClassLoader to be garbage collected,
 * the entire ClassLoader instance must become unreachable (no strong references).
 * Creating separate instances per ObjectMapper allows them to be independently
 * garbage collected when their associated ObjectMapper is discarded.</p>
 *
 * <p>Recommended usage: one DynamicClassLoader per ObjectMapper to ensure
 * proper isolation and cleanup.</p>
 *
 * ANDROID_COMPATIBLE - Android build provides a stub implementation
 */
@com.alibaba.fastjson3.annotation.JVMOnly
public class DynamicClassLoader
        extends ClassLoader {
    private static final Map<String, Class<?>> CLASS_MAPPING;
    private static final DynamicClassLoader SHARED_INSTANCE = new DynamicClassLoader();

    /**
     * Weak reference to a loaded class, used for automatic cleanup.
     */
    private static final class WeakClassReference extends WeakReference<Class<?>> {
        final String className;

        WeakClassReference(Class<?> referent, String className, ReferenceQueue<Class<?>> queue) {
            super(referent, queue);
            this.className = className;
        }
    }

    /**
     * Map of class names to weak references of loaded classes.
     * When a class is no longer referenced elsewhere, the weak reference
     * is cleared and the entry can be removed.
     */
    private final ConcurrentHashMap<String, WeakClassReference> classes = new ConcurrentHashMap<>();

    /**
     * Reference queue for tracking cleared weak references.
     */
    private final ReferenceQueue<Class<?>> referenceQueue = new ReferenceQueue<>();

    static {
        Class<?>[] preloaded = {
                Object.class,
                java.lang.reflect.Type.class,
                java.lang.reflect.Field.class,
                java.lang.reflect.Method.class,

                // core3 types
                com.alibaba.fastjson3.JSONParser.class,
                com.alibaba.fastjson3.JSONGenerator.class,
                com.alibaba.fastjson3.ObjectReader.class,
                com.alibaba.fastjson3.ObjectWriter.class,
                com.alibaba.fastjson3.JSONObject.class,
                com.alibaba.fastjson3.JSONArray.class,
                com.alibaba.fastjson3.JSONException.class,
                com.alibaba.fastjson3.ObjectMapper.class,
                com.alibaba.fastjson3.reader.FieldReader.class,
                com.alibaba.fastjson3.reader.FieldNameMatcher.class,
                com.alibaba.fastjson3.writer.FieldWriter.class,
                com.alibaba.fastjson3.util.JDKUtils.class,

                // JDK types
                java.util.Collection.class,
                java.util.Set.class,
                java.util.List.class,
                java.util.ArrayList.class,
                java.util.LinkedList.class,
                java.util.Map.class,
                java.util.HashMap.class,
                java.util.LinkedHashMap.class,
                java.util.function.Supplier.class,

                Exception.class,
                Enum.class,
                Class.class,
                Boolean.class,
                Byte.class,
                Short.class,
                Integer.class,
                Long.class,
                Float.class,
                Double.class,
                String.class,
                java.math.BigInteger.class,
                java.math.BigDecimal.class,
        };
        java.util.Map<String, Class<?>> mapping = new java.util.HashMap<>();
        for (Class<?> clazz : preloaded) {
            mapping.put(clazz.getName(), clazz);
        }
        CLASS_MAPPING = Collections.unmodifiableMap(mapping);
    }

    public DynamicClassLoader() {
        this(getParentClassLoader());
    }

    public DynamicClassLoader(ClassLoader parent) {
        super(parent);
        exportInternalPackagesToThisLoader();
    }

    /**
     * Classes defined via {@link ClassLoader#defineClass} land in this loader's
     * unnamed module. ASM-generated readers/writers reference internal helpers
     * in {@code com.alibaba.fastjson3.util} (JDKUtils, UnsafeAllocator) which
     * is NOT exported by the {@code com.alibaba.fastjson3} module — so without
     * an explicit cross-module export, calls from the generated code fail with
     * {@link IllegalAccessError} at link time when the library is used from a
     * JPMS modulepath (e.g. Maven surefire in module mode). Open the needed
     * internal packages to this loader's unnamed module at construction time.
     */
    private void exportInternalPackagesToThisLoader() {
        Module fj3Module = DynamicClassLoader.class.getModule();
        if (!fj3Module.isNamed()) {
            return; // classpath mode — JPMS rules don't apply
        }
        try {
            Module target = this.getUnnamedModule();
            fj3Module.addExports("com.alibaba.fastjson3.util", target);
            fj3Module.addExports("com.alibaba.fastjson3.internal.asm", target);
        } catch (Throwable t) {
            // Unusual classloader scenarios (OSGi, framework containers) may
            // throw on Module.addExports. Falling back silently is acceptable
            // — in classpath-style deployments the generated code already
            // works without this call, and JPMS-strict users will get a
            // clear IllegalAccessError pointing at the missing exports.
        }
    }

    static ClassLoader getParentClassLoader() {
        ClassLoader contextClassLoader = Thread.currentThread().getContextClassLoader();
        if (contextClassLoader != null) {
            try {
                contextClassLoader.loadClass(DynamicClassLoader.class.getName());
                return contextClassLoader;
            } catch (ClassNotFoundException e) {
                // skip
            }
        }
        return DynamicClassLoader.class.getClassLoader();
    }

    @Override
    protected Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundException {
        Class<?> mappingClass = CLASS_MAPPING.get(name);
        if (mappingClass != null) {
            return mappingClass;
        }

        // Clean up stale entries first
        cleanUp();

        WeakClassReference ref = classes.get(name);
        Class<?> clazz = ref != null ? ref.get() : null;
        if (clazz != null) {
            return clazz;
        }

        ClassNotFoundException error;
        try {
            return super.loadClass(name, resolve);
        } catch (ClassNotFoundException e) {
            error = e;
        }

        ClassLoader tcl = Thread.currentThread().getContextClassLoader();
        if (tcl != null && tcl != this) {
            try {
                return tcl.loadClass(name);
            } catch (ClassNotFoundException ignored) {
            }
        }

        throw error;
    }

    /**
     * Load a class from bytecode and track it with a weak reference.
     *
     * @param name the class name
     * @param b    the bytecode
     * @param off  offset in the byte array
     * @param len  length of the bytecode
     * @return the loaded class
     * @throws ClassFormatError if the bytecode is invalid
     */
    public Class<?> loadClass(String name, byte[] b, int off, int len) throws ClassFormatError {
        // Check if already defined (fast path without cleanup)
        WeakClassReference existingRef = classes.get(name);
        if (existingRef != null) {
            Class<?> existing = existingRef.get();
            if (existing != null && classes.get(name) == existingRef) {
                return existing;
            }
        }

        // Clean up stale entries before expensive defineClass operation
        cleanUp();

        // Use compute to atomically check and define
        WeakClassReference newRef = classes.compute(name, (key, existing) -> {
            // If another thread already defined it, use that
            if (existing != null) {
                Class<?> clazz = existing.get();
                if (clazz != null) {
                    return existing;
                }
            }

            // Define the class
            Class<?> clazz = defineClass(name, b, off, len);
            return new WeakClassReference(clazz, name, referenceQueue);
        });

        // Get the class from the reference (handle the unlikely case of immediate GC)
        Class<?> clazz = newRef.get();
        if (clazz == null) {
            // Reference was cleared immediately (very rare), retry
            return loadClass(name, b, off, len);
        }
        return clazz;
    }

    /**
     * Clean up entries whose weak references have been cleared.
     */
    private void cleanUp() {
        Reference<? extends Class<?>> ref;
        while ((ref = referenceQueue.poll()) != null) {
            if (ref instanceof WeakClassReference wcr) {
                classes.remove(wcr.className, wcr);
            }
        }
    }

    /**
     * Get the shared singleton instance.
     * Used by ObjectMapper.shared() for compatibility.
     *
     * @return the shared instance
     */
    public static DynamicClassLoader getSharedInstance() {
        return SHARED_INSTANCE;
    }

    /**
     * Get the shared instance (backward compatibility).
     *
     * @deprecated Use {@link #getSharedInstance()} instead
     */
    @Deprecated
    public static DynamicClassLoader getInstance() {
        return SHARED_INSTANCE;
    }

    /**
     * Get the number of classes currently tracked by this classloader.
     * Useful for testing and monitoring.
     *
     * @return the number of tracked classes
     */
    public int getTrackedClassCount() {
        cleanUp();
        return classes.size();
    }
}
